on:
  workflow_dispatch:
  # schedule:
  # - cron: "0 2 * * *"
jobs:
  my_job:
    name: test job
    runs-on: ubuntu-latest

    steps:
      - name: Install Java
        run: sudo apt-get install openjdk-11-jre 
      - name: Fetch Latest Release
        id: fetch-latest-release
        uses: gregziegan/fetch-latest-release@v2.0.0
        with:
          repo_path: ReVanced/revanced-cli
      # get output from previous step
      - run: echo "Latest Release is ${{ steps.fetch-latest-release.outputs.tag_name }}"
      - run: echo "Name is ${{ steps.fetch-latest-release.outputs.name }}"
      - name: Fetch Github Release Asset
        uses: dsaltares/fetch-gh-release-asset@1.1.1
        with:
          # The `org/repo` containing the release.
          repo: 'ReVanced/revanced-cli'
          # The release version to fetch from in the form `tags/<tag_name>` or `<release_id>`.
          # version: # optional, default is latest
          # The name of the file to be downloaded.
          file: "revanced-cli-.*\\.jar"
          # Target file path.
          target: 'revanced-cli.jar'
          # The GitHub token. Typically this will be secrets.GITHUB_TOKEN
          # token: # optional, default is ${{ github.token }}
          # Use regex for file input
          regex: true
      # download is done, now use the downloaded jar file
      - run: ls -l
      - run: java -jar revanced-cli.jar -h
          
    
